site_name: OmicsBridge
nav:
  - Home: index.md
  - Database and Data Upload: Database.md
  - Count & Comparison Data Overview: Data_Overview.md
  - Compare Across Datasets: Compare_across_datasets.md
  - Two Datasets Integration: integrate_two.md
  - Clinical Data Analysis: Clinical_data.md
  - scRNA Data Overview: scRNA.md
  - Epigenome Visualisation: igv.md
  - Custom Gene Sets: Gene_set.md
  - Tools: Tools.md
  - FAQ: FAQ.md
  - Case study: Case_study.md
theme:
  name: material
  features:
    - navigation.top
    - navigation.tracking
    - toc.follow
    - content.code.copy
extra_css:
  - css/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
